---
title: "Exploratory Analyses and Reporting"
author: "You, Scientist"
format: html
execute:
  keep-md: true
---

```{r include = FALSE}
library(tidyverse)
#library(palmerpenguins)
library(kableExtra)

penguins <- read_csv("data/penguins_samp1.csv")
```

## Activity Objectives

Throughout this activity, you'll practice the following skills.

+ Documenting and communicating a technical analysis.
+ Conducting exploratory analyses and communicative the results of those analyses transparently and clearly.
+ Connecting exploratory analyses to hypothesis generation, transparently communicating your process and highlighting that hypotheses will be tested on data which was held out during your exploratory analysis.

## Your Tasks

Please complete the following tasks. 

1. Re-open the R Project you created last time and open your Hypothesis Generating notebook.
2. In your notebook, write a short abstract. At this point, that abstract will briefly introduce your topic/subject and the main questions you've decided to answer.
3. Write an introduction to that report. Your introduction should describe the topic you are working on. That is, the introduction should include general information about the topic (organism, subsystem, etc.) as well as the data set and the available features/variables.
4. Annotate your exploratory analysis with a robust narrative discussing the analysis you undertook, describing your plots and summary statistics, and also justifying how that analysis connects back to your main question(s) of interest.
5. Describe the hypotheses you've generated as a result of your exploratory analysis.
6. Use the *Git* tab in the top-right of your RStudio window to `Pull -> Commit -> Push` changes to your Repository on GitHub.

When all of this is done, you should have three subsections of a technical report completed. These are the *abstract*, the *introduction*, and the *exploratory analysis*. We'll add to this report in the next notebook.


